FIFA-Corp/fitnest

netlify.toml
=> adding netlify toml

package-lock.json, package.json, src/component/product-container.tsx, src/component/ui/card/index.ts, src/component/ui/card/product-card.tsx, src/routes/home.tsx, src/types/index.ts, src/types/product-type.ts, tailwind.config.cjs
=> Implement product card and container component Close #31

package-lock.json, src/component/brand-container.tsx, src/component/category-container.tsx, src/component/layout/navbar.tsx, src/component/product-container.tsx, src/component/ui/card/brand-category-card.tsx, src/component/ui/card/product-card.tsx, src/routes/home.tsx, src/routes/products/productId.tsx
1. Move brand container to the top of the page
2. Change the currency to rupiah
3. Comment "100 Terjual" on the product card
=> Improvement layout and formatting

src/routes/products/productId.tsx, src/types/index.ts, src/types/product-type.ts, src/types/size-quantity-type.ts
Adding feature size quanity in product detail
=> Adding feature size quanity in product detail

package-lock.json, package.json, src/component/button-add-to-cart.tsx, src/component/layout/cart.tsx, src/component/layout/index.tsx, src/component/layout/navbar.tsx, src/component/ui/card/cart-product-card.tsx, src/component/ui/card/index.ts, src/libs/index.ts, src/libs/local-storage.ts, src/libs/recoil.ts, src/main.tsx, src/routes/404.tsx, src/routes/products/productId.tsx, src/services/cart/add-to-cart.ts, src/services/cart/detele-cart.ts, src/services/index.ts, src/types/cart-type.ts, src/types/index.ts
=> Add feature cart

src/services/cart/add-to-cart.ts
=> change model data cart

src/component/layout/cart.tsx, src/component/ui/card/cart-product-card.tsx, src/routes/products/productId.tsx
=> using mutate to re render swr

src/component/layout/cart.tsx, src/routes/products/productId.tsx
Adding optional chaining in image
=> Adding optional chaining in image

src/component/layout/cart.tsx, src/component/ui/card/cart-product-card.tsx
=> add logic total price

src/component/layout/navbar.tsx, src/main.tsx, src/routes/products/products.tsx
=> Add feature search

src/component/layout/navbar.tsx
=> add total cart in navbar

package-lock.json, src/component/layout/navbar.tsx, src/libs/headers.ts, src/libs/local-storage.ts, src/main.tsx, src/routes/home.tsx, src/routes/login.tsx, src/routes/register.tsx, src/services/auth/check-auth.ts, src/services/auth/login.ts, src/services/auth/logout.ts, src/services/auth/register.ts, src/services/index.ts, src/types/index.ts, src/types/login-type.ts, src/types/register-type.ts, tailwind.config.cjs
=> Add feature auth (Close #36)

src/component/layout/navbar.tsx
fixing add condition before get user data
=> fixing add condition before get user data

package-lock.json, src/component/banner.tsx, src/component/layout/cart.tsx, src/component/layout/index.tsx, src/component/layout/navbar.tsx, src/component/ui/card/cart-product-card.tsx, src/context/auth-context.tsx, src/context/index.ts, src/libs/headers.ts, src/libs/recoil.ts, src/main.tsx, src/routes/login.tsx, src/routes/products/productId.tsx, src/routes/register.tsx, src/services/auth/check-auth.ts, src/services/auth/login.ts, src/services/auth/register.ts, src/services/cart/add-to-cart.ts, src/services/cart/detele-cart.ts
=> Add feature cart with auth

src/component/layout/cart.tsx, src/component/layout/navbar.tsx, src/component/ui/card/checkout-product-card.tsx, src/component/ui/card/index.ts, src/main.tsx, src/routes/checkout.tsx
=> Add feature checkout

src/component/layout/navbar.tsx, src/routes/products/products.tsx
Handle submit search with FormData, URLSearchParams, navigate
=> Handle submit search without rerender to whole app

src/component/brand-container.tsx, src/component/category-container.tsx, src/component/ui/card/brand-category-card.tsx, src/routes/checkout.tsx
Add feature click category and brand card to product filter by category or brand
=> Add feature click category and brand card to product filter by category or brand Close #62

src/component/layout/index.tsx, src/component/layout/navbar.tsx, src/component/ui/card/checkout-product-card.tsx, src/routes/checkout.tsx
- Close #67 button logout is show after user logout
- Close #70 Quantity and size in product page
- Close #71 Add scroll restoration
=> fix button logout scroll restoration quantity checkout

src/component/layout/footer.tsx, src/component/ui/card/cart-product-card.tsx, src/routes/products/products.tsx
fix language to indonesian at cart  and add padding to products page
=> fix language and padding

src/component/layout/navbar.tsx, src/component/ui/card/checkout-product-card.tsx, src/component/ui/card/transaction-card.tsx, src/main.tsx, src/routes/checkout.tsx, src/routes/transaction.tsx, src/services/cart/add-to-cart.ts, src/services/checkout/buy.ts, src/types/form-checkout-type.ts, src/types/index.ts, src/types/transaction-type.ts
=> Add logic checkout and transaction page

src/component/brand-container.tsx, src/component/category-container.tsx
remove lihat semua button on brand-container and category-container
=> fix: remove "lihat semua" button

src/component/layout/cart.tsx
fix product is available in cart but web show not found
=> fix product is available in cart but web show not found

README.md
=> Update readme Close #72

src/routes/products/productId.tsx
fix can't scroll when open cart
=> fix can't scroll when open cart

README.md
remove redundant text in README
=> remove redundant text in README
